### PR TITLE
PL-161-Sideview-close-buttons-on-the-wrong-place

### PR DESCRIPTION
**Pull request by gabrielekarra**
Removed the node that was displayed

### CODE REVIEW

**Comment by NinaGnjidic** [comment]
I did not test locally, but if it works it’s +1 from me

**Comment by gabrielekarra** [comment]
@NinaGnjidic so i can merge this?

**Comment by gabrielekarra** [comment]
@NinaGnjidic i fixed it here

**Comment by tonesija** [comment]
summaryx still wrong
In summary it's still misplaced.

**Comment by tonesija** [comment]
Also in the reference view.

**Comment by gabrielekarra** [comment]
> summaryx still wrong In summary it's still misplaced.

this is fixed in pl 160

**Comment by tonesija** [comment]
> > summaryx still wrong In summary it's still misplaced.
> 
> this is fixed in pl 160, alredy in the main

But it's still outside the sidebar. I don't know where to put it, but it looks like a but like this. Maybe it would be better to remove the X button and just close the summaries when you click on the button again.

**Comment by gabrielekarra** [comment]
> > > summaryx still wrong In summary it's still misplaced.
> > 
> > 
> > this is fixed in pl 160, alredy in the main
> 
> But it's still outside the sidebar. I don't know where to put it, but it looks like a but like this. Maybe it would be better to remove the X button and just close the summaries when you click on the button again.

just because this branch is aheda main from some commit

**Comment by NinaGnjidic** [comment]
Honestly, I needed to change things a lot in side view in #91 so I even deleted removed this button completely and used one is side window with changing it's style depending if knowledge graph or summary is displayed. Because of this, in my opinion, you can close this PR without merging or if you really want to you can merge it, but as I said everything will be changed in the end because of #91 ....

**Pull request closed without merging**
