### PR TITLE
NOREF: Acceptance Tests

### PR DESCRIPTION
**Pull request by paolocorsa**
DONE:

- TA-01 - PDF Upload
- TA-02 - Open a new document
- TA-03 - Next/previous page (using PDFL tools)
- TA-04 - Next/Previous page (with keyboard shortcuts)
- TA-05 - Jump to selected page
- TA-06 - Scrolling
- TA-07 - Zooming (with PDFL tools)
- TA-08 - Zooming (with Kkeyboar shortcuts)
- TA-10 - Visualize the document
- TA-12 - URL
- TA-14 - Open Knowledge Graph
- TA-15 - Building the nowledge Graph
- TA-17 - Availability Cross-References
- TA-18 - Open Cross-References
- TA-19 - Open Cross-References (images, tables, chapter …)
- TA-20 - Open summary section
- TA-21 - Open TLDR, Abstract, Abstract summary section in the summary layout

Tested Manually:

- TA-09 - Full screen (with PDFL tool)
- TA-11 - Full screen (with Keyboard Shortcuts)
- TA-13 - Selectable text
- TA-16 - Knowledge graph interaction
- TA-22 - Summarize selected text
- TA-23 - Highlighting key components

### CODE REVIEW

**Comment by paolocorsa** [comment]
ADDED: 
-TA-06
-TA-10
-TA-12

TODO:
-TA-09 and TA-11 are for FULL SCREEN but it throw an uncatched exception (full screen exception) 
-From TA-12 to TA-25

**Comment by paolocorsa** [comment]
I don't know how because yesterday night it worked but TA-02 doesn't work anymore because when you click on "Open a new PDF", it throws a uncaught exception:
image

**Comment by NinaGnjidic** [comment]
> I don't know how because yesterday night it worked but TA-02 doesn't work anymore because when you click on "Open a new PDF", it throws a uncaught exception: image
> 
> I don't know also why in the test application some test fail when in local they run successfully.

This is an existing bug, that has been fixed permanently in my refactoring task and in Tonio's reset reader task... To make things work for you, add this if statement to #hidePdfReferenceToShowGraph method in ReferenceViewComponent:
image

**Comment by Giamburrasca** [comment]
Really well done @paolocorsa !!

**Comment by paolocorsa** [comment]
> > I don't know how because yesterday night it worked but TA-02 doesn't work anymore because when you click on "Open a new PDF", it throws a uncaught exception: image
> > 
> > I don't know also why in the test application some test fail when in local they run successfully.
> 
> This is an existing bug, that has been fixed permanently in my refactoring task and in Tonio's reset reader task... To make things work for you, add this if statement to #hidePdfReferenceToShowGraph method in ReferenceViewComponent:
> image
> 
> Also, you're doing really good work here man, keep doing what you're doing 👍 

Thank you!
You saved it 🫡
I'll try later.

**Comment by tonesija** [comment]
> > I don't know how because yesterday night it worked but TA-02 doesn't work anymore because when you click on "Open a new PDF", it throws a uncaught exception: image
> > I don't know also why in the test application some test fail when in local they run successfully.
> 
> This is an existing bug, that has been fixed permanently in my refactoring task and in Tonio's reset reader task... To make things work for you, add this if statement to #hidePdfReferenceToShowGraph method in ReferenceViewComponent: image
> 
> Also, you're doing really good work here man, keep doing what you're doing 👍

Fixed in cypress

**Comment by NinaGnjidic** [comment]
This can now be merged to main i assume so +1

**Comment by Giamburrasca** [comment]
I think everything is being tested, so +1 also for me

**Pull request merged**
