### PR TITLE
PL-159 CSS fixed to not stretch the reference view

### PR DESCRIPTION
**Pull request by Giamburrasca**
TO DO:
- fix the UI with the correct uniform style

DONE:
- page reference view not stretched anymore
- zoom blocked
- scroll disabled on the reference view

### CODE REVIEW

**Comment by paolocorsa** [comment]
When you open the sideview and then open a new pdf it is not aligned and it doesn't close the previous side view:
Screenshot_20221231_122149
The sideview on the right is from a previous document and not the actual one.
But the problem is fixed, there is not any stretching.

**Comment by gabrielekarra** [comment]
before this i think is better to do the refactor, this pr can be a child of it

**Comment by Giamburrasca** [comment]
> When you open the sideview and then open a new pdf it is not aligned and it doesn't close the previous side view:
> Screenshot_20221231_122149
> The sideview on the right is from a previous document and not the actual one.
> But the problem is fixed, there is not any stretching.

Fixed with a new event (then maybe we will realize it better with some EventHandler)

**Comment by NinaGnjidic** [comment]
It's not stretched anymore and it's position is fixed which is great, but looks kinda weird... This is how it looks like when I initially open a reference close button's position is a bit off (overlaps with navbar):
image
I scroll down a bit, close button is lost and there's this white background:
image

**Pull request merged**
